#!/usr/bin/env python3
"""Rename the lines this repository imported from rizin's sigdb-source.

The first commit of this repository imported pattern files generated by
rizin. Their bytes are ordinary FLIRT patterns, but their names follow
rizin's conventions: every character outside [A-Za-z0-9_.] became `_`, names
were cut at 125 characters, and some lines were named after sections or
labels instead of functions. NeverD's rule is the linkage name the library's
symbol table spells (see README.md). This script moves every imported line to
that rule where the evidence allows it, and leaves the rest untouched.

For each imported line, in order:

1. By bytes. neverd-sigmaker runs over the collected libraries with a leading
   pattern long enough to state every byte of every function. If the bytes
   an imported line states agree with those functions under exactly one
   name, the line takes that name.
2. By spelling. If the bytes settle nothing, the line takes the one library
   name that rizin's conversion turns into the imported name. When no name
   or more than one name converts to it, this step settles nothing.
3. A line named after a section (`.text_tii_131`, `.lf_1`) or a label
   (`_LN116`) names no function at all, so it is removed.
4. Every other line stays exactly as it was and is listed in the report.

Knowledge of rizin's conventions lives here and nowhere else. This script
exists to undo one import; NeverD itself never needs it.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path

# Directory of each collector architecture, and the neverd-sigmaker machine.
TARGETS = {
    "x86": ("pe/x86/32", "x86"),
    "x64": ("pe/x86/64", "x64"),
    "arm": ("pe/arm/32", "arm"),
    "arm64": ("pe/arm/64", "arm64"),
}

# Long enough that the leading pattern states the whole function.
WHOLE_FUNCTION = 65535

RIZIN_NAME_LIMIT = 125
_RIZIN_UNSAFE = re.compile(r"[^A-Za-z0-9_.]")

# Names rizin gave to things that are not functions.
_SECTION_NAME = re.compile(r"^\.[A-Za-z_]")
_LABEL_NAME = re.compile(r"^_LN\d+$")


def rizin_spelling(name: str) -> str:
    """How rizin's import spelled a linkage name."""

    return _RIZIN_UNSAFE.sub("_", name)[:RIZIN_NAME_LIMIT]


def is_artifact(name: str) -> bool:
    return bool(_SECTION_NAME.match(name) or _LABEL_NAME.match(name))


def crc16(data: bytes) -> int:
    """neverd::sigs::SignatureMatcher::computeCRC16."""

    crc = 0xFFFF
    for byte in data:
        crc ^= byte
        for _ in range(8):
            crc = (crc >> 1) ^ 0x8408 if crc & 1 else crc >> 1
    crc = ~crc & 0xFFFF
    return ((crc << 8) | (crc >> 8)) & 0xFFFF


def parse_hex(text: str) -> tuple[bytes, bytes]:
    """Pattern bytes as (values, mask); a mask byte of 0 is a wildcard."""

    if len(text) % 2:
        raise ValueError(f"odd-length pattern {text[:40]}")
    values = bytearray()
    mask = bytearray()
    for index in range(0, len(text), 2):
        pair = text[index : index + 2]
        if pair == "..":
            values.append(0)
            mask.append(0)
        else:
            values.append(int(pair, 16))
            mask.append(1)
    return bytes(values), bytes(mask)


@dataclass
class Line:
    lead: str
    crc_len: int
    crc: int
    total: int
    name: str
    tail: str
    extra: list[str]

    @classmethod
    def parse(cls, text: str) -> "Line":
        tokens = text.split()
        if len(tokens) < 6 or tokens[4] != ":0000":
            raise ValueError(f"unexpected line shape: {text[:120]}")
        tail = ""
        extra = tokens[6:]
        if extra and not extra[0].startswith(":"):
            tail = extra[0]
            extra = extra[1:]
        if extra:
            raise ValueError(f"more than one name on an imported line: {text[:120]}")
        return cls(tokens[0], int(tokens[1], 16), int(tokens[2], 16), int(tokens[3], 16),
                   tokens[5], tail, extra)

    def render(self, name: str) -> str:
        text = f"{self.lead} {self.crc_len:02X} {self.crc:04X} {self.total:04X} :0000 {name}"
        return f"{text} {self.tail}" if self.tail else text


@dataclass
class Function:
    name: str
    values: bytes
    mask: bytes


class Reference:
    """Every function of one target, byte for byte, with its linkage name."""

    def __init__(self) -> None:
        self.by_shape: dict[tuple[int, int], list[Function]] = defaultdict(list)
        self.by_spelling: dict[str, set[str]] = defaultdict(set)
        self.names = 0
        self.too_long = 0

    def add_line(self, text: str) -> None:
        tokens = text.split()
        values, mask = parse_hex(tokens[0])
        total = int(tokens[3], 16)
        if len(values) < total:
            # Longer than the leading pattern can state; nothing to compare.
            self.too_long += 1
            return
        name = tokens[5]
        function = Function(name, values[:total], mask[:total])
        first = values[0] if total and mask[0] else -1
        self.by_shape[(total, first)].append(function)
        self.by_spelling[rizin_spelling(name)].add(name)
        self.names += 1

    def candidates(self, total: int, first: int | None) -> list[Function]:
        found = list(self.by_shape.get((total, -1), ()))
        if first is None:
            for (length, _), functions in self.by_shape.items():
                if length == total:
                    found.extend(functions)
            return found
        return found + list(self.by_shape.get((total, first), ()))


def agrees(line: Line, lead: tuple[bytes, bytes], tail: tuple[bytes, bytes],
           function: Function) -> bool | None:
    """Whether a line's bytes agree with a function's.

    Returns None when they agree wherever both state a byte but the CRC span
    covers a byte the function leaves to a relocation, so the CRC cannot be
    checked.
    """

    values, mask = function.values, function.mask
    lead_values, lead_mask = lead
    for index in range(min(len(lead_values), line.total)):
        if lead_mask[index] and mask[index] and lead_values[index] != values[index]:
            return False
    crc_start = len(lead_values)
    crc_end = crc_start + line.crc_len
    if crc_end > line.total:
        return False
    checked = True
    if line.crc_len:
        if all(mask[crc_start:crc_end]):
            if crc16(values[crc_start:crc_end]) != line.crc:
                return False
        else:
            checked = False
    tail_values, tail_mask = tail
    for offset in range(min(len(tail_values), line.total - crc_end)):
        index = crc_end + offset
        if tail_mask[offset] and mask[index] and tail_values[offset] != values[index]:
            return False
    return True if checked else None


@dataclass
class FileReport:
    lines: int = 0
    by_bytes: int = 0
    by_spelling: int = 0
    already_conforming: int = 0
    removed_artifacts: int = 0
    unresolved: int = 0
    unresolved_names: list[str] = field(default_factory=list)
    removed_names: list[str] = field(default_factory=list)


def resolve(line: Line, reference: Reference) -> tuple[str | None, str]:
    """The linkage name for an imported line, and how it was found."""

    lead = parse_hex(line.lead)
    tail = parse_hex(line.tail) if line.tail else (b"", b"")
    first = lead[0][0] if lead[1] and lead[1][0] else None
    strong: set[str] = set()
    weak: set[str] = set()
    for function in reference.candidates(line.total, first):
        verdict = agrees(line, lead, tail, function)
        if verdict:
            strong.add(function.name)
        elif verdict is None:
            weak.add(function.name)
    names = strong or weak
    if len(names) == 1:
        return next(iter(names)), "bytes"
    if names:
        # The bytes are shared; the imported spelling may still pick one.
        spelled = {name for name in names if rizin_spelling(name) == line.name}
        if len(spelled) == 1:
            return next(iter(spelled)), "bytes"
    spelled = reference.by_spelling.get(line.name, set())
    if len(spelled) == 1:
        return next(iter(spelled)), "spelling"
    return None, "unresolved"


def migrate_file(path: Path, reference: Reference, report: FileReport) -> list[str]:
    output = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        text = raw.strip()
        if not text or text.startswith((";", "#")) or text == "---":
            output.append(raw)
            continue
        line = Line.parse(text)
        report.lines += 1
        if is_artifact(line.name):
            report.removed_artifacts += 1
            report.removed_names.append(line.name)
            continue
        name, how = resolve(line, reference)
        if name is None:
            report.unresolved += 1
            report.unresolved_names.append(line.name)
            output.append(text)
            continue
        if name == line.name:
            report.already_conforming += 1
        elif how == "bytes":
            report.by_bytes += 1
        else:
            report.by_spelling += 1
        output.append(line.render(name))
    return output


def build_reference(sigmaker: Path, assets: Path, arch: str, work: Path) -> Reference:
    reference = Reference()
    machine = TARGETS[arch][1]
    manifests = sorted(assets.glob(f"*-{arch}.json"))
    if not manifests:
        raise SystemExit(f"no {arch} assets in {assets}")
    for manifest_path in manifests:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        unpacked = work / manifest["asset"]
        unpacked.mkdir(parents=True)
        subprocess.run(
            ["tar", "--zstd", "-xf", str(assets / manifest["archive"]["name"]), "-C", str(unpacked)],
            check=True,
        )
        libraries = sorted(
            str(path) for path in unpacked.rglob("*")
            if path.is_file() and path.suffix.lower() in (".lib", ".obj")
        )
        out = work / f"{manifest['asset']}.ref.pat"
        subprocess.run(
            [str(sigmaker), *libraries, "-o", str(out), "--machine", machine,
             "--leading", str(WHOLE_FUNCTION), "--tail", "0", "--min-size", "1"],
            check=True, stdout=subprocess.DEVNULL,
        )
        for text in out.read_text(encoding="utf-8").splitlines():
            if text.strip():
                reference.add_line(text)
        shutil.rmtree(unpacked)
        out.unlink()
    return reference


def imported_files(tree: Path, revision: str, directory: str) -> list[Path]:
    listing = subprocess.run(
        ["git", "-C", str(tree), "ls-tree", "--name-only", f"{revision}:{directory}"],
        check=True, capture_output=True, text=True,
    ).stdout.split()
    return [tree / directory / name for name in listing if name.endswith(".pat")]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--sigmaker", type=Path, required=True)
    parser.add_argument("--assets", type=Path, required=True,
                        help="directory with the library release's archives and manifests")
    parser.add_argument("--tree", type=Path, default=Path("."),
                        help="the signatures repository checkout")
    parser.add_argument("--imported-from", default="0a3da7a",
                        help="the commit that imported the rizin files")
    parser.add_argument("--arch", action="append", choices=sorted(TARGETS),
                        help="architectures to migrate (default: those with imported files)")
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--work", type=Path, default=None)
    args = parser.parse_args(argv)

    summary: dict[str, dict] = {}
    for arch in args.arch or sorted(TARGETS):
        directory = TARGETS[arch][0]
        try:
            files = imported_files(args.tree, args.imported_from, directory)
        except subprocess.CalledProcessError:
            files = []
        if not files:
            continue
        with tempfile.TemporaryDirectory(dir=args.work) as scratch:
            reference = build_reference(args.sigmaker, args.assets, arch, Path(scratch))
        print(f"{directory}: {reference.names} reference functions", flush=True)
        for path in files:
            report = FileReport()
            lines = migrate_file(path, reference, report)
            path.write_text("\n".join(lines) + "\n", encoding="utf-8")
            key = path.relative_to(args.tree).as_posix()
            summary[key] = report.__dict__
            print(
                f"{key}: {report.lines} lines, {report.by_bytes} renamed by bytes, "
                f"{report.by_spelling} by spelling, {report.already_conforming} already "
                f"conforming, {report.removed_artifacts} non-function lines removed, "
                f"{report.unresolved} unresolved",
                flush=True,
            )
    args.report.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    totals = Counter()
    for report in summary.values():
        for key in ("lines", "by_bytes", "by_spelling", "already_conforming",
                    "removed_artifacts", "unresolved"):
            totals[key] += report[key]
    print(f"total: {dict(totals)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
