#!/usr/bin/env python3
"""Rename the lines this repository imported from rizin's sigdb-source.

The first commit of this repository imported pattern files generated by
rizin. Their bytes are ordinary FLIRT patterns, but their names follow
rizin's conventions, not NeverD's:

  * PE names had every character outside [A-Za-z0-9_.] turned into `_` and
    were cut at 125 characters (`?Close@CFile@@UEAAXXZ` became
    `_Close_CFile__UEAAXXZ`).
  * ELF C++ names were demangled, had every character outside
    [A-Za-z0-9_.:] turned into `_` and trailing `_` dropped, and some were
    rewritten as `method.<class>.<member>`.
  * Some lines were named after sections, labels or data objects
    (`.text_tii_131`, `_LN116`, `obj.once.9977`), none of which is a function.
  * Many lines state their tail from the end of the leading pattern, with the
    CRC span written as wildcards, where the format -- and NeverD's matcher --
    starts the tail after the CRC span. Such a tail is compared crclen bytes
    too early and all but never matches.

NeverD's rule is the linkage name the library's symbol table spells (see
README.md), and a tail that starts where the CRC span ends. This script
moves every imported line to those rules where the evidence allows it, and
leaves the rest untouched. For each line, in order:

0. The tail. A tail whose first crclen bytes are not all wildcards starts
   after the CRC span already. One longer than the function has room for
   after the CRC span starts at the end of the leading pattern, and those
   crclen wildcards are dropped so that it starts where NeverD reads it. For
   a tail that could be either, the reference bytes decide; without them, the
   file decides when at least 95% of the lines it settles agree.
   A line that then states fewer than 16 bytes exactly is removed:
   neverd-sigmaker never writes one, because it names far more code than the
   function it was made from.
1. By bytes. neverd-sigmaker runs over the same libraries with a leading
   pattern long enough to state every byte of every function. If the bytes
   an imported line states agree with those functions under exactly one
   name, the line takes that name when the imported name is that
   function's rizin spelling, or names nothing, like a section or a label.
   Bytes of a function the import does not name are shared by two routines,
   so the line is removed. So is one whose bytes agree in full with
   functions of several names: NeverD drops such a byte claim from
   the files it builds, because any one name would be a guess, and the
   imported name is a guess as well. So is a line whose bytes open a longer
   function of another name, since NeverD's matcher compares a line only as
   far as its own length: it would name that function too.
2. A line named after a section, label or data object that the bytes did not
   settle names no function, so it is removed.
3. By spelling. The line takes the one library name that rizin's conversion
   turns into the imported name. When no name or more than one name converts
   to it, this step settles nothing either.
4. A PE C name. Every decorated C++ name holds "@@", which rizin spelled
   "__", so a name without "__" past its leading underscores is a C name
   rizin left as it was. On 32-bit x86, "_name_N" is also how rizin spelled
   the stdcall "_name@N"; it becomes that only when the routine ends in
   `ret N`, and otherwise stays unresolved.
5. Every other line is kept as a comment, which the loader does not read,
   and is listed in the report.

Every run starts from the text of the import commit, so what a file holds
depends only on the import, the reference libraries and these rules, and the
report describes a single pass. A file with a provenance record
(`<name>.sources.json`) is rebuilt from collected libraries and holds no
imported line, so it is left alone.

Knowledge of rizin's conventions lives here and nowhere else. This script
exists to undo one import; NeverD itself never needs it.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path

from coff_symbols import code_symbols

# The PE directory of each collector architecture, and its sigmaker machine.
PE_TARGETS = {
    "x86": ("pe/x86/32", "x86"),
    "x64": ("pe/x86/64", "x64"),
    "arm": ("pe/arm/32", "arm"),
    "arm64": ("pe/arm/64", "arm64"),
}

# Long enough that the leading pattern states the whole function.
WHOLE_FUNCTION = 65535

PE_NAME_LIMIT = 125
ELF_NAME_LIMIT = 1023

# Every line covers at least this many bytes (see MIN_STATED_BYTES), so a
# line that opens a longer function agrees with it this far.
OPENING = 16

# neverd::sigs::SignatureMatcher::MinStatedBytes: neverd-sigmaker never writes
# a line that states fewer bytes exactly, because such a line agrees with a
# great deal of unrelated code.
MIN_STATED_BYTES = 16

# How <name>.imported keeps a line it cannot give a linkage name: as a
# comment, which neither the loader nor the builder reads.
UNRESOLVED = "; unresolved:"

_PE_UNSAFE = re.compile(r"[^A-Za-z0-9_.]")
_ELF_UNSAFE = re.compile(r"[^A-Za-z0-9_.:]")

_PE_ARTIFACT = re.compile(r"^(\.[A-Za-z_].*|_LN\d+)$")
_ELF_ARTIFACT = re.compile(r"^(obj\..+|\.[A-Za-z_].*)$")

# Names rizin's conversion leaves exactly as the symbol table spells them: C
# identifiers. A decorated PE name always begins with `?`, which rizin turned
# into `_`, so only a PE name that starts with a letter is known to be one; a
# demangled ELF name has `::`, an argument list or a `method.` prefix.
_PE_VERBATIM = re.compile(r"^[A-Za-z][A-Za-z0-9_]*$")

# A function compiled with -ffunction-sections sits alone in `.text.<symbol>`,
# and rizin named some lines after that section.
_ELF_SECTION_SYMBOL = re.compile(
    r"^\.text\.(?:(?:unlikely|hot|startup|exit|split)\.)?(?P<symbol>[A-Za-z_$][A-Za-z0-9_.$]*)$")

# The directory whose functions have the other pointer width, where an
# imported line filed under the wrong one belongs.
SIBLINGS = {
    "elf/arm/64": "elf/arm/32", "elf/arm/32": "elf/arm/64",
    "elf/x86/64": "elf/x86/32", "elf/x86/32": "elf/x86/64",
    "pe/x86/64": "pe/x86/32", "pe/x86/32": "pe/x86/64",
}
_ELF_VERBATIM = re.compile(r"^[A-Za-z_][A-Za-z0-9_.$]*$")


def pe_spelling(name: str) -> str:
    """How rizin's import spelled a PE linkage name."""

    return _PE_UNSAFE.sub("_", name)[:PE_NAME_LIMIT]


def elf_spellings(demangled: str) -> set[str]:
    """The ways rizin's import spelled an ELF function, given its demangled name.

    The plain form is the demangled name made safe. The method form splits it
    at the last `::` before the first `(` -- wherever that falls, template
    arguments and `(anonymous namespace)` included -- into `method.<class>.<rest>`.
    """

    plain = _ELF_UNSAFE.sub("_", demangled).rstrip("_")
    forms = {plain[:ELF_NAME_LIMIT].rstrip("_")}
    paren = demangled.find("(")
    head = demangled if paren < 0 else demangled[:paren]
    cut = head.rfind("::")
    if cut >= 0:
        owner = _ELF_UNSAFE.sub("_", demangled[:cut])
        member = _ELF_UNSAFE.sub("_", demangled[cut + 2 :]).rstrip("_")
        forms.add(f"method.{owner}.{member}"[:ELF_NAME_LIMIT].rstrip("_"))
    return forms


def is_artifact(name: str, binary_format: str) -> bool:
    pattern = _PE_ARTIFACT if binary_format == "pe" else _ELF_ARTIFACT
    return bool(pattern.match(name))


def section_symbol(name: str, binary_format: str) -> str | None:
    """The function a line named after its `.text.<symbol>` section holds."""

    if binary_format != "elf":
        return None
    match = _ELF_SECTION_SYMBOL.match(name)
    return match.group("symbol") if match else None


def is_verbatim(name: str, binary_format: str) -> bool:
    """Whether rizin's import cannot have changed this name."""

    if binary_format == "pe":
        # A character rizin's conversion replaces means it never touched the name.
        return bool(_PE_VERBATIM.match(name) or _PE_UNSAFE.search(name))
    return bool(_ELF_VERBATIM.match(name)) and not name.startswith("method.")


_STDCALL_SPELLING = re.compile(r"^(?P<stem>_[A-Za-z0-9_.]*?)_(?P<size>[0-9]+)$")


def c_linkage_name(line: Line, reference: "Reference") -> str | None:
    """The linkage name of a C function whose spelling rizin left intact.

    Every decorated MSVC C++ function name holds "@@", which rizin spelled
    "__", so a PE name with no "__" past its leading underscores is a C name,
    and rizin kept it as it was. On 32-bit x86 there is one exception: the
    stdcall "_name@N" became "_name_N", which a cdecl name can be as well.
    That spelling is settled only when the routine ends in `ret N`, which the
    stdcall routine does and the cdecl one does not.
    """

    name = line.name
    if reference.binary_format != "pe" or not name.startswith("_"):
        return None
    if "__" in name.lstrip("_") or _PE_UNSAFE.search(name):
        return None
    match = _STDCALL_SPELLING.match(name) if reference.callee_cleanup else None
    if match is None:
        return name
    size = int(match.group("size"))
    if size % 4:
        # A stdcall routine pops whole stack slots.
        return name
    ending = [line.byte_at(line.total - back) for back in (3, 2, 1)]
    if size and size <= 0xFFFF and ending == [0xC2, size & 0xFF, size >> 8]:
        return f"{match.group('stem')}@{size}"
    return None


def crc16(data: bytes) -> int:
    """neverd::sigs::SignatureMatcher::computeCRC16."""

    crc = 0xFFFF
    for byte in data:
        crc ^= byte
        for _ in range(8):
            crc = (crc >> 1) ^ 0x8408 if crc & 1 else crc >> 1
    crc = ~crc & 0xFFFF
    return ((crc << 8) | (crc >> 8)) & 0xFFFF


_MASK_TABLE = str.maketrans({c: "\x01" for c in "0123456789ABCDEFabcdef"} | {".": "\x00"})


def parse_hex(text: str) -> tuple[bytes, bytes]:
    """Pattern bytes as (values, mask); a mask byte of 0 is a wildcard."""

    if len(text) % 2:
        raise ValueError(f"odd-length pattern {text[:40]}")
    values = bytes.fromhex(text.replace("..", "00"))
    # Each pair is either ".." or two hex digits, so its first character
    # says which.
    mask = text[0::2].translate(_MASK_TABLE).encode("latin-1")
    return values, mask


def demangle(names: list[str]) -> list[str]:
    """Demangle Itanium names the way rizin's demangler printed them.

    That is libiberty without DMGL_VERBOSE: `std::string::rbegin() const`,
    not `std::basic_string<char, ...>::rbegin() const`, which is what plain
    c++filt prints. `c++filt -i` turns the verbose expansion off.
    """

    if not names:
        return []
    completed = subprocess.run(
        ["c++filt", "-i"], input="\n".join(names) + "\n", capture_output=True, text=True,
        check=True,
    )
    lines = completed.stdout.split("\n")
    if len(lines) < len(names):
        raise RuntimeError("c++filt returned fewer names than it was given")
    return lines[: len(names)]


@dataclass
class Line:
    lead: str
    crc_len: int
    crc: int
    total: int
    name: str
    tail: str

    @classmethod
    def parse(cls, text: str) -> "Line":
        tokens = text.split()
        if len(tokens) < 6 or tokens[4] != ":0000":
            raise ValueError(f"unexpected line shape: {text[:120]}")
        rest = tokens[6:]
        tail = ""
        if rest and not rest[0].startswith(":"):
            tail, rest = rest[0], rest[1:]
        if rest:
            raise ValueError(f"more than one name on an imported line: {text[:120]}")
        return cls(tokens[0], int(tokens[1], 16), int(tokens[2], 16), int(tokens[3], 16),
                   tokens[5], tail)

    def tail_style(self) -> str:
        """'after-crc', 'after-lead', or 'either' for the tail's alignment."""

        if not self.tail or not self.crc_len:
            return "trivial"
        run = 0
        for index in range(0, len(self.tail), 2):
            if self.tail[index : index + 2] != "..":
                break
            run += 1
        if run < self.crc_len:
            return "after-crc"
        lead_len = len(self.lead) // 2
        if len(self.tail) // 2 > self.total - lead_len - self.crc_len:
            return "after-lead"
        return "either"

    def realigned(self) -> "Line":
        """This line with a tail stated from the end of the leading pattern
        moved to start after the CRC span."""

        tail = self.tail[2 * self.crc_len :].rstrip(".") if self.tail else ""
        room = max(0, self.total - len(self.lead) // 2 - self.crc_len)
        return Line(self.lead, self.crc_len, self.crc, self.total, self.name, tail[: 2 * room])

    def byte_at(self, offset: int) -> int | None:
        """The byte the line states at a routine offset, or None.

        The CRC span states only its bytes' checksum, and a wildcard nothing.
        """

        lead_len = len(self.lead) // 2
        if offset < 0 or offset >= self.total:
            return None
        if offset < lead_len:
            text = self.lead[2 * offset : 2 * offset + 2]
        else:
            index = offset - lead_len - self.crc_len
            if index < 0:
                return None
            text = self.tail[2 * index : 2 * index + 2]
        return int(text, 16) if len(text) == 2 and text != ".." else None

    def stated_bytes(self) -> int:
        """Bytes the line states exactly, as NeverD's matcher reads it."""

        lead = self.lead[: 2 * self.total]
        stated = sum(1 for index in range(0, len(lead), 2) if lead[index] != ".")
        room = max(0, self.total - len(self.lead) // 2)
        stated += min(self.crc_len, room)
        room = max(0, room - self.crc_len)
        tail = self.tail[: 2 * room]
        stated += sum(1 for index in range(0, len(tail), 2) if tail[index] != ".")
        return stated

    def render(self, name: str) -> str:
        text = f"{self.lead} {self.crc_len:02X} {self.crc:04X} {self.total:04X} :0000 {name}"
        return f"{text} {self.tail}" if self.tail else text


@dataclass
class Function:
    name: str
    values: bytes
    mask: bytes


class Reference:
    """Every function of one target directory, byte for byte, with its name."""

    def __init__(self, binary_format: str) -> None:
        self.binary_format = binary_format
        self.by_shape: dict[tuple[int, int], list[Function]] = defaultdict(list)
        self.by_spelling: dict[str, set[str]] = defaultdict(set)
        self.demangled: dict[str, str] = {}
        self.by_name: dict[str, list[Function]] = defaultdict(list)
        # Functions by their first OPENING bytes, as stated or relocated.
        self.by_opening: dict[tuple[bytes, bytes], list[Function]] = defaultdict(list)
        self.names: set[str] = set()
        # The names each collected Visual Studio release's libraries define in
        # their code sections, whether or not neverd-sigmaker wrote a line.
        self.defined: dict[str, set[str]] = defaultdict(set)
        # 32-bit x86, where the callee-cleanup conventions decorate C names.
        self.callee_cleanup = False
        self._seen: set[int] = set()
        self.functions = 0
        self.too_long = 0

    def add_line(self, text: str) -> None:
        tokens = text.split()
        name = tokens[5]
        # Builds of one library share most functions byte for byte.
        identity = hash((name, tokens[0], tokens[3]))
        if identity in self._seen:
            return
        self._seen.add(identity)
        values, mask = parse_hex(tokens[0])
        total = int(tokens[3], 16)
        self.names.add(name)
        if len(values) < total:
            # Longer than the leading pattern can state; only the name is usable.
            self.too_long += 1
            return
        first = values[0] if total and mask[0] else -1
        function = Function(name, values[:total], mask[:total])
        self.by_shape[(total, first)].append(function)
        self.by_name[name].append(function)
        if total > OPENING:
            self.by_opening[(values[:OPENING], mask[:OPENING])].append(function)
        self.functions += 1

    def index_spellings(self) -> None:
        names = sorted(self.names)
        if self.binary_format == "pe":
            for name in names:
                spelling = pe_spelling(name)
                self.by_spelling[spelling].add(name)
                # A name cut at the limit lost the underscores it then ended
                # with ("...QEAAPEAV_" was imported as "...QEAAPEAV").
                self.by_spelling[spelling.rstrip("_")].add(name)
            return
        for name, demangled in zip(names, demangle(names)):
            self.demangled[name] = demangled
            for spelling in elf_spellings(demangled):
                self.by_spelling[spelling].add(name)
            # C names demangle to themselves and were imported verbatim.
            self.by_spelling[name].add(name)

    def candidates(self, total: int, first: int | None) -> list[Function]:
        found = list(self.by_shape.get((total, -1), ()))
        if first is None:
            for (length, leading), functions in self.by_shape.items():
                if length == total and leading != -1:
                    found.extend(functions)
            return found
        return found + list(self.by_shape.get((total, first), ()))

    def one_routine(self, names: set[str]) -> str | None:
        """The name to use when several names are one routine, else None.

        An Itanium constructor or destructor has several symbols (C1/C2,
        D0/D1/D2) that label one definition and demangle identically; any of
        them names the code correctly, so the smallest is taken.
        """

        if len(names) > 1 and self.binary_format == "elf":
            forms = {self.demangled.get(name) for name in names}
            if len(forms) == 1 and None not in forms:
                return min(names)
        return None

    def spelled(self, imported: str) -> set[str]:
        # Spellings are cut at the import's length limit when they are
        # indexed, so a name the import truncated is found exactly.
        return self.by_spelling.get(imported, set())


def agrees(line: Line, lead: tuple[bytes, bytes], tail: tuple[bytes, bytes],
           function: Function) -> bool | None:
    """Whether a line's bytes agree with a function's.

    Returns None when they agree wherever both state a byte but the CRC span
    covers a byte the function leaves to a relocation, so the CRC cannot be
    checked.
    """

    values, mask = function.values, function.mask
    lead_values, lead_mask = lead
    for index in range(min(len(lead_values), line.total)):
        if lead_mask[index] and mask[index] and lead_values[index] != values[index]:
            return False
    crc_start = len(lead_values)
    crc_end = crc_start + line.crc_len
    # A routine shorter than the leading pattern has its lead padded with
    # wildcards and no CRC span; like NeverD's matcher, compare it only as
    # far as its length.
    if line.crc_len and crc_end > line.total:
        return False
    checked = True
    if line.crc_len:
        if all(mask[crc_start:crc_end]):
            if crc16(values[crc_start:crc_end]) != line.crc:
                return False
        else:
            checked = False
    tail_values, tail_mask = tail
    for offset in range(min(len(tail_values), line.total - crc_end)):
        index = crc_end + offset
        if tail_mask[offset] and mask[index] and tail_values[offset] != values[index]:
            return False
    return True if checked else None


def agreeing_names(line: Line, reference: Reference) -> tuple[set[str], set[str]]:
    """The names of the functions a line's bytes agree with.

    The first set holds the functions it agrees with fully; the second those
    it agrees with wherever both state a byte, but whose relocations keep the
    CRC from being checked.
    """

    lead = parse_hex(line.lead)
    tail = parse_hex(line.tail) if line.tail else (b"", b"")
    first = lead[0][0] if lead[1] and lead[1][0] else None
    strong: set[str] = set()
    weak: set[str] = set()
    for function in reference.candidates(line.total, first):
        verdict = agrees(line, lead, tail, function)
        if verdict:
            strong.add(function.name)
        elif verdict is None:
            weak.add(function.name)
    return strong, weak


def by_bytes(line: Line, reference: Reference) -> set[str]:
    strong, weak = agreeing_names(line, reference)
    return strong or weak


def among(line: Line, names: set[str], reference: Reference) -> set[str]:
    """The names whose functions a line's stated bytes agree with.

    Only ever asked about names the spelling already narrowed down to, so the
    function may run longer than the imported line says: rizin measured
    functions by analysis, neverd-sigmaker by symbol extent, and the two
    disagree about trailing padding and split-off cold parts.
    """

    lead = parse_hex(line.lead)
    tail = parse_hex(line.tail) if line.tail else (b"", b"")
    agreeing = set()
    for name in names:
        for function in reference.by_name.get(name, ()):
            if len(function.values) < line.total:
                continue
            clipped = Function(name, function.values[: line.total], function.mask[: line.total])
            if agrees(line, lead, tail, clipped):
                agreeing.add(name)
    return agreeing


def opening_names(line: Line, reference: Reference) -> set[str]:
    """The names of longer functions whose opening bytes a line states in full.

    NeverD's matcher compares a line only as far as the line's own length,
    so such a line matches the start of each of them. Only functions that
    state or relocate the same first bytes as the line are compared.
    """

    lead = parse_hex(line.lead)
    tail = parse_hex(line.tail) if line.tail else (b"", b"")
    if len(lead[0]) < OPENING or line.total < OPENING:
        return set()
    key = (lead[0][:OPENING], lead[1][:OPENING])
    names = set()
    for function in reference.by_opening.get(key, ()):
        if len(function.values) <= line.total or function.name in names:
            continue
        clipped = Function(function.name, function.values[: line.total],
                           function.mask[: line.total])
        if agrees(line, lead, tail, clipped):
            names.add(function.name)
    return names


def resolve(line: Line, reference: Reference) -> tuple[str | None, str]:
    """The linkage name for an imported line, and how it was settled."""

    name, how = settle(line, reference)
    if how in ("ambiguous", "artifact"):
        return name, how
    own = name if name is not None else line.name
    others = opening_names(line, reference) - {own}
    if others and reference.one_routine(others | {own}) is None:
        return None, "opening"
    return name, how


def settle(line: Line, reference: Reference) -> tuple[str | None, str]:
    """The name the bytes and the spelling give a line, before openings."""

    strong, weak = agreeing_names(line, reference)
    spelled = reference.spelled(line.name)
    symbol = section_symbol(line.name, reference.binary_format)
    # The names the import can stand for. A line named after a label or a
    # section-relative artifact names nothing, so its bytes alone decide.
    named = spelled | {line.name} | ({symbol} if symbol else set())
    anonymous = symbol is None and is_artifact(line.name, reference.binary_format)
    if strong:
        routine = strong if len(strong) == 1 or reference.one_routine(strong) else None
        if routine is None:
            # The collected libraries hold exactly these bytes under several
            # names. NeverD drops such a claim from the files it builds,
            # because any one name would be a guess, and the imported spelling
            # is no better: kept, the line names every routine with them.
            return None, "ambiguous"
        chosen = routine & named if not anonymous else routine
        if not chosen:
            # The bytes are another routine's than the one the import names:
            # two routines share them, so neither name identifies the code.
            return None, "ambiguous"
        return (next(iter(chosen)) if len(chosen) == 1
                else reference.one_routine(chosen) or min(chosen)), "bytes"
    if weak:
        # The CRC could not be checked, so the bytes only confirm a name the
        # import already points at.
        chosen = weak if anonymous else weak & named
        if len(chosen) == 1:
            return next(iter(chosen)), "bytes"
        alias = reference.one_routine(chosen)
        if alias is not None:
            return alias, "bytes"
    if symbol is not None:
        return symbol, "section"
    if is_artifact(line.name, reference.binary_format):
        return None, "artifact"
    if len(spelled) == 1:
        return next(iter(spelled)), "spelling"
    alias = reference.one_routine(spelled)
    if alias is not None:
        return alias, "spelling"
    if len(spelled) > 1:
        # Several names spell the same; the bytes may still tell them apart.
        agreeing = among(line, spelled, reference)
        if len(agreeing) == 1:
            return next(iter(agreeing)), "bytes"
        alias = reference.one_routine(agreeing)
        if alias is not None:
            return alias, "bytes"
    elif is_verbatim(line.name, reference.binary_format):
        return line.name, "verbatim"
    else:
        c_name = c_linkage_name(line, reference)
        if c_name is not None:
            return c_name, "verbatim" if c_name == line.name else "stdcall"
    return None, "unresolved"


@dataclass
class FileReport:
    lines: int = 0
    by_bytes: int = 0
    by_spelling: int = 0
    already_conforming: int = 0
    from_section: int = 0
    moved: int = 0
    verbatim: int = 0
    removed_artifacts: int = 0
    removed_weak: int = 0
    removed_ambiguous: int = 0
    removed_openings: int = 0
    reproduced: int = 0
    superseded: int = 0
    unresolved: int = 0
    realigned_tails: int = 0
    undecided_tails: int = 0
    unresolved_names: list[str] = field(default_factory=list)
    removed_names: list[str] = field(default_factory=list)
    weak_names: list[str] = field(default_factory=list)
    ambiguous_names: list[str] = field(default_factory=list)
    opening_names: list[str] = field(default_factory=list)


def file_tail_style(lines: list[Line]) -> str | None:
    """The alignment a file's undecided tails take: that of at least 95% of
    the tails the file settles, or None."""

    styles = Counter(line.tail_style() for line in lines)
    settled = styles["after-crc"] + styles["after-lead"]
    if not settled:
        return None
    for style in ("after-crc", "after-lead"):
        if styles[style] >= 0.95 * settled:
            return style
    return None


def align(line: Line, reference: Reference, default: str | None) -> tuple[Line, str]:
    style = line.tail_style()
    if style == "either":
        early = line.realigned()
        as_is = bool(by_bytes(line, reference))
        moved = bool(by_bytes(early, reference))
        if as_is == moved:
            # Function extents differ between rizin and neverd-sigmaker, so
            # the strict comparison often says nothing; compare against the
            # functions the imported name can stand for instead.
            spelled = reference.spelled(line.name)
            if spelled:
                as_is = bool(among(line, spelled, reference))
                moved = bool(among(early, spelled, reference))
        if as_is != moved:
            style = "after-crc" if as_is else "after-lead"
        elif default is not None:
            style = default
        else:
            return line, "undecided"
    if style == "after-lead":
        return line.realigned(), "realigned"
    return line, "kept"


def migrate_file(path: Path, reference: Reference, report: FileReport,
                 sibling: Reference | None = None,
                 moved: list[str] | None = None,
                 defined: set[str] | None = None) -> list[str]:
    """The migrated lines of an imported file.

    `defined` is not None when the file's own libraries were collected; its
    file is then built anew from them. A line whose bytes a collected
    function of the same name states in full is left out as reproduced. When
    those libraries are the build the import was made from, `defined` holds
    every name they define, and a line with one of them is left out too:
    they hold that routine, and the line neverd-sigmaker made for it -- or
    its decision to make none, for code its rules reject -- stands. For
    another build of the same sources it is empty.

    A line still unresolved, in any file, is kept as a comment, which the
    loader does not read: a name in rizin's spelling is no linkage name.
    """

    texts = path.read_text(encoding="utf-8").splitlines()
    parsed = [
        Line.parse(raw.strip())
        for raw in texts
        if raw.strip() and not raw.strip().startswith((";", "#")) and raw.strip() != "---"
    ]
    default = file_tail_style(parsed)
    output = []
    for raw in texts:
        text = raw.strip()
        if not text or text.startswith((";", "#")) or text == "---":
            output.append(raw)
            continue
        line, alignment = align(Line.parse(text), reference, default)
        report.lines += 1
        if line.stated_bytes() < MIN_STATED_BYTES:
            # NeverD never writes such a line; it names far more code than
            # the function it was made from.
            report.removed_weak += 1
            report.weak_names.append(line.name)
            continue
        if alignment == "realigned":
            report.realigned_tails += 1
            text = line.render(line.name)
        elif alignment == "undecided":
            report.undecided_tails += 1
        name, how = resolve(line, reference)
        if how == "ambiguous":
            report.removed_ambiguous += 1
            report.ambiguous_names.append(line.name)
            continue
        if how == "opening":
            report.removed_openings += 1
            report.opening_names.append(line.name)
            continue
        if how == "artifact":
            report.removed_artifacts += 1
            report.removed_names.append(line.name)
            continue
        if name is None and sibling is not None and moved is not None:
            # Some imported lines were filed under the wrong pointer width;
            # only the bytes of a function of the other width may move one.
            other, other_how = resolve(line, sibling)
            if other_how in ("ambiguous", "opening"):
                # Code of the other width that several routines share names
                # none of them, in either directory.
                report.removed_ambiguous += 1
                report.ambiguous_names.append(line.name)
                continue
            if other is not None and other_how == "bytes":
                report.moved += 1
                moved.append(line.render(other))
                continue
        if name is None:
            report.unresolved += 1
            report.unresolved_names.append(line.name)
            output.append(f"{UNRESOLVED} {text}")
            continue
        if defined is not None:
            strong, _ = agreeing_names(line, reference)
            if name in strong or (strong and reference.one_routine(strong | {name})):
                report.reproduced += 1
                continue
            if name in defined:
                report.superseded += 1
                continue
        if how == "verbatim":
            report.verbatim += 1
        elif how == "stdcall":
            # The routine's `ret N` decided between cdecl and stdcall.
            report.by_bytes += 1
        elif how == "section":
            report.from_section += 1
        elif name == line.name:
            report.already_conforming += 1
        elif how == "bytes":
            report.by_bytes += 1
        else:
            report.by_spelling += 1
        output.append(line.render(name))
    return output


def build_pe_reference(sigmaker: Path, assets: Path, arch: str, work: Path) -> Reference:
    reference = Reference("pe")
    reference.callee_cleanup = arch == "x86"
    machine = PE_TARGETS[arch][1]
    manifests = sorted(assets.glob(f"*-{arch}.json"))
    if not manifests:
        raise SystemExit(f"no {arch} assets in {assets}")
    for manifest_path in manifests:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        unpacked = work / manifest["asset"]
        unpacked.mkdir(parents=True)
        subprocess.run(
            ["tar", "--zstd", "-xf", str(assets / manifest["archive"]["name"]), "-C", str(unpacked)],
            check=True,
        )
        libraries = sorted(
            str(path) for path in unpacked.rglob("*")
            if path.is_file() and path.suffix.lower() in (".lib", ".obj")
        )
        release = asset_release(manifest)
        for library in libraries:
            names = code_symbols(Path(library))
            # Every name a library defines can be one an import spelled,
            # including those of code neverd-sigmaker writes no line for.
            reference.names |= names
            if release is not None:
                reference.defined[release] |= names
        out = work / f"{manifest['asset']}.ref.pat"
        subprocess.run(
            [str(sigmaker), *libraries, "-o", str(out), "--machine", machine,
             "--leading", str(WHOLE_FUNCTION), "--tail", "0", "--min-size", "1"],
            check=True, stdout=subprocess.DEVNULL,
        )
        for text in out.read_text(encoding="utf-8").splitlines():
            if text.strip():
                reference.add_line(text)
        shutil.rmtree(unpacked)
        out.unlink()
    reference.index_spellings()
    return reference


def load_reference(directory: Path, binary_format: str) -> Reference:
    """Reference lines already generated, one or more .pat files per target."""

    reference = Reference(binary_format)
    reference.callee_cleanup = directory.as_posix().endswith("pe/x86/32")
    files = sorted(directory.glob("*.pat"))
    if not files:
        raise SystemExit(f"no reference .pat files in {directory}")
    for path in files:
        for text in path.read_text(encoding="utf-8").splitlines():
            if text.strip():
                reference.add_line(text)
    reference.index_spellings()
    return reference


def imported_files(tree: Path, revision: str, directory: str) -> list[Path]:
    try:
        listing = subprocess.run(
            ["git", "-C", str(tree), "ls-tree", "--name-only", f"{revision}:{directory}"],
            check=True, capture_output=True, text=True,
        ).stdout.split()
    except subprocess.CalledProcessError:
        return []
    # A file with a provenance record is rebuilt from collected libraries.
    # It holds no imported line any more, unless its release keeps the lines
    # those libraries do not define in <name>.imported, which the migration
    # writes anew.
    return [
        tree / directory / name
        for name in listing
        if name.endswith(".pat")
        and (
            not (tree / directory / name).with_suffix(".sources.json").exists()
            or (tree / directory / name).with_suffix(".imported").exists()
        )
    ]


def restore(tree: Path, revision: str, path: Path) -> None:
    """Put a file's imported text back, so that every run starts from it."""

    relative = path.relative_to(tree).as_posix()
    text = subprocess.run(
        ["git", "-C", str(tree), "show", f"{revision}:{relative}"],
        check=True, capture_output=True, text=True,
    ).stdout
    path.write_text(text, encoding="utf-8")


def release_of(path: Path) -> str:
    """The release a file is built for, as asset_release names it: its stem."""

    return path.stem


def asset_release(manifest: dict) -> str | None:
    """The file an asset's libraries build: vs<year> or the library's own name."""

    if manifest.get("kind") == "toolset":
        return f"vs{int(manifest['visual_studio']['year'])}"
    if manifest.get("kind") == "library":
        return str(manifest["library"])
    return None


def collected_releases(assets: Path, arch: str) -> dict[str, bool]:
    """The releases whose libraries the assets hold for arch, and whether
    those libraries are the build the import was made from.

    A Visual Studio release's collected libraries are its release-to-
    manufacturing libraries, which rizin's were. A library asset says so
    itself (`reproduces_import`): the MASM32 SDK builds the same sources with
    the same assembler, but zlib compiled here is not the build rizin made.
    """

    releases: dict[str, bool] = {}
    for manifest_path in assets.glob(f"*-{arch}.json"):
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        release = asset_release(manifest)
        if release is None:
            continue
        same = manifest.get("kind") == "toolset" or bool(manifest.get("reproduces_import"))
        releases[release] = releases.get(release, True) and same
    return releases


def migrate_directory(tree: Path, revision: str, directory: str, files: list[Path],
                      reference: Reference, summary: dict[str, dict],
                      verify_with: Path | None,
                      sibling: Reference | None = None,
                      moves: dict[Path, list[str]] | None = None,
                      collected: dict[str, bool] | None = None) -> None:
    collected = collected or {}
    print(f"{directory}: {reference.functions} reference functions, "
          f"{len(reference.names)} names", flush=True)
    for path in files:
        restore(tree, revision, path)
        report = FileReport()
        moved: list[str] = []
        release = release_of(path)
        rebuilt = release in collected
        # Only the build the import was made from supersedes a line by name;
        # another build leaves out only the lines whose bytes it reproduces.
        defined = ((reference.defined.get(release, set()) if collected[release] else set())
                   if rebuilt else None)
        lines = migrate_file(path, reference, report, sibling, moved, defined=defined)
        if moved and moves is not None:
            moves.setdefault(tree / SIBLINGS[directory] / path.name, []).extend(moved)
        # A release whose libraries were collected gets its file built anew;
        # what the libraries cannot reproduce joins it from <name>.imported.
        written = path.with_suffix(".imported") if rebuilt else path
        written.write_text("\n".join(lines) + "\n", encoding="utf-8")
        if verify_with is not None:
            # The loader rejects a whole directory for one bad line.
            subprocess.run([str(verify_with), "--verify", str(written)], check=True,
                           stdout=subprocess.DEVNULL)
        key = written.relative_to(tree).as_posix()
        summary[key] = report.__dict__
        print(
            f"{key}: {report.lines} lines, {report.by_bytes} renamed by bytes, "
            f"{report.by_spelling} by spelling, {report.from_section} from their section, "
            f"{report.moved} moved to the other width, "
            f"{report.already_conforming} already conforming, {report.verbatim} C names kept, "
            f"{report.removed_artifacts} non-function lines removed, "
            f"{report.removed_weak} lines stating under {MIN_STATED_BYTES} bytes removed, "
            f"{report.removed_ambiguous} lines whose bytes several library routines share "
            f"removed, {report.removed_openings} whose bytes open a longer routine removed, "
            f"{report.reproduced} reproduced by collected libraries, "
            f"{report.superseded} superseded by what they define, "
            f"{report.unresolved} unresolved; {report.realigned_tails} tails realigned, "
            f"{report.undecided_tails} undecided",
            flush=True,
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--tree", type=Path, default=Path("."),
                        help="the signatures repository checkout")
    parser.add_argument("--imported-from", default="0a3da7a",
                        help="the commit that imported the rizin files")
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--work", type=Path, default=None)
    parser.add_argument("--verify-with", type=Path, default=None,
                        help="neverd-sigmaker to read every rewritten file back with")
    pe = parser.add_argument_group("PE directories, referenced from a library release")
    pe.add_argument("--sigmaker", type=Path)
    pe.add_argument("--assets", type=Path,
                    help="directory with the library release's archives and manifests")
    pe.add_argument("--arch", action="append", choices=sorted(PE_TARGETS), default=[])
    other = parser.add_argument_group("any directory, referenced from generated lines")
    other.add_argument("--directory", action="append", default=[],
                       help="target directory such as elf/x86/64 (repeatable)")
    other.add_argument("--references", type=Path,
                       help="root holding <directory>/*.pat reference lines")
    args = parser.parse_args(argv)

    summary: dict[str, dict] = {}
    for arch in args.arch:
        if args.sigmaker is None or args.assets is None:
            parser.error("--arch needs --sigmaker and --assets")
        directory = PE_TARGETS[arch][0]
        files = imported_files(args.tree, args.imported_from, directory)
        if not files:
            continue
        with tempfile.TemporaryDirectory(dir=args.work) as scratch:
            reference = build_pe_reference(args.sigmaker, args.assets, arch, Path(scratch))
        migrate_directory(args.tree, args.imported_from, directory, files, reference, summary,
                          args.verify_with, collected=collected_releases(args.assets, arch))
    moves: dict[Path, list[str]] = {}
    for directory in args.directory:
        if args.references is None:
            parser.error("--directory needs --references")
        files = imported_files(args.tree, args.imported_from, directory)
        if not files:
            continue
        binary_format = directory.split("/")[0]
        reference = load_reference(args.references / directory, binary_format)
        sibling = None
        sibling_directory = args.references / SIBLINGS.get(directory, "-")
        if directory in SIBLINGS and sibling_directory.is_dir():
            sibling = load_reference(sibling_directory, binary_format)
        migrate_directory(args.tree, args.imported_from, directory, files, reference, summary,
                          args.verify_with, sibling, moves)

    # Moved lines are already in NeverD's form, so they join their new file
    # only after every file has been migrated.
    for destination, lines in sorted(moves.items()):
        existing = destination.read_text(encoding="utf-8").splitlines() if destination.is_file() else []
        seen = set(existing)
        added = [line for line in lines if line not in seen and not seen.add(line)]
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text("\n".join(existing + added) + "\n", encoding="utf-8")
        if args.verify_with is not None:
            subprocess.run([str(args.verify_with), "--verify", str(destination)], check=True,
                           stdout=subprocess.DEVNULL)
        key = destination.relative_to(args.tree).as_posix()
        summary.setdefault(key, FileReport().__dict__)["received"] = len(added)
        print(f"{key}: {len(lines)} lines moved here from the other width, "
              f"{len(lines) - len(added)} of them already present", flush=True)

    args.report.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    totals = Counter()
    for report in summary.values():
        for key in ("lines", "by_bytes", "by_spelling", "from_section", "moved",
                    "already_conforming", "verbatim", "removed_artifacts", "removed_weak",
                    "removed_ambiguous", "removed_openings", "reproduced", "superseded",
                    "unresolved",
                    "realigned_tails", "undecided_tails"):
            totals[key] += report.get(key, 0)
    print(f"total: {dict(totals)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
