#!/usr/bin/env python3
"""Rename the lines this repository imported from rizin's sigdb-source.

The first commit of this repository imported pattern files generated by
rizin. Their bytes are ordinary FLIRT patterns, but their names follow
rizin's conventions, not NeverD's:

  * PE names had every character outside [A-Za-z0-9_.] turned into `_` and
    were cut at 125 characters (`?Close@CFile@@UEAAXXZ` became
    `_Close_CFile__UEAAXXZ`).
  * ELF C++ names were demangled, had every character outside
    [A-Za-z0-9_.:] turned into `_` and trailing `_` dropped, and some were
    rewritten as `method.<class>.<member>`.
  * Some lines were named after sections, labels or data objects
    (`.text_tii_131`, `_LN116`, `obj.once.9977`), none of which is a function.
  * Many lines state their tail from the end of the leading pattern, with the
    CRC span written as wildcards, where the format -- and NeverD's matcher --
    starts the tail after the CRC span. Such a tail is compared crclen bytes
    too early and all but never matches.

NeverD's rule is the linkage name the library's symbol table spells (see
README.md), and a tail that starts where the CRC span ends. This script
moves every imported line to those rules where the evidence allows it, and
leaves the rest untouched. For each line, in order:

0. The tail. A tail whose first crclen bytes are not all wildcards starts
   after the CRC span already. One longer than the function has room for
   after the CRC span starts at the end of the leading pattern, and those
   crclen wildcards are dropped so that it starts where NeverD reads it. For
   a tail that could be either, the reference bytes decide; without them, the
   file decides when at least 95% of the lines it settles agree.
1. By bytes. neverd-sigmaker runs over the same libraries with a leading
   pattern long enough to state every byte of every function. If the bytes
   an imported line states agree with those functions under exactly one
   name, the line takes that name.
2. A line named after a section, label or data object that the bytes did not
   settle names no function, so it is removed.
3. By spelling. The line takes the one library name that rizin's conversion
   turns into the imported name. When no name or more than one name converts
   to it, this step settles nothing either.
4. Every other line stays exactly as it was, and is listed in the report.

Knowledge of rizin's conventions lives here and nowhere else. This script
exists to undo one import; NeverD itself never needs it.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path

# The PE directory of each collector architecture, and its sigmaker machine.
PE_TARGETS = {
    "x86": ("pe/x86/32", "x86"),
    "x64": ("pe/x86/64", "x64"),
    "arm": ("pe/arm/32", "arm"),
    "arm64": ("pe/arm/64", "arm64"),
}

# Long enough that the leading pattern states the whole function.
WHOLE_FUNCTION = 65535

PE_NAME_LIMIT = 125
ELF_NAME_LIMIT = 1023
_PE_UNSAFE = re.compile(r"[^A-Za-z0-9_.]")
_ELF_UNSAFE = re.compile(r"[^A-Za-z0-9_.:]")

_PE_ARTIFACT = re.compile(r"^(\.[A-Za-z_].*|_LN\d+)$")
_ELF_ARTIFACT = re.compile(r"^(obj\..+|\.[A-Za-z_].*)$")

# Names rizin's conversion leaves exactly as the symbol table spells them: C
# identifiers. A decorated PE name always begins with `?`, which rizin turned
# into `_`, so only a PE name that starts with a letter is known to be one; a
# demangled ELF name has `::`, an argument list or a `method.` prefix.
_PE_VERBATIM = re.compile(r"^[A-Za-z][A-Za-z0-9_]*$")
_ELF_VERBATIM = re.compile(r"^[A-Za-z_][A-Za-z0-9_.$]*$")


def pe_spelling(name: str) -> str:
    """How rizin's import spelled a PE linkage name."""

    return _PE_UNSAFE.sub("_", name)[:PE_NAME_LIMIT]


def elf_spellings(demangled: str) -> set[str]:
    """The ways rizin's import spelled an ELF function, given its demangled name.

    The plain form is the demangled name made safe. The method form splits it
    at the last `::` before the first `(` -- wherever that falls, template
    arguments and `(anonymous namespace)` included -- into `method.<class>.<rest>`.
    """

    plain = _ELF_UNSAFE.sub("_", demangled).rstrip("_")
    forms = {plain[:ELF_NAME_LIMIT].rstrip("_")}
    paren = demangled.find("(")
    head = demangled if paren < 0 else demangled[:paren]
    cut = head.rfind("::")
    if cut >= 0:
        owner = _ELF_UNSAFE.sub("_", demangled[:cut])
        member = _ELF_UNSAFE.sub("_", demangled[cut + 2 :]).rstrip("_")
        forms.add(f"method.{owner}.{member}"[:ELF_NAME_LIMIT].rstrip("_"))
    return forms


def is_artifact(name: str, binary_format: str) -> bool:
    pattern = _PE_ARTIFACT if binary_format == "pe" else _ELF_ARTIFACT
    return bool(pattern.match(name))


def is_verbatim(name: str, binary_format: str) -> bool:
    """Whether rizin's import cannot have changed this name."""

    if binary_format == "pe":
        return bool(_PE_VERBATIM.match(name))
    return bool(_ELF_VERBATIM.match(name)) and not name.startswith("method.")


def crc16(data: bytes) -> int:
    """neverd::sigs::SignatureMatcher::computeCRC16."""

    crc = 0xFFFF
    for byte in data:
        crc ^= byte
        for _ in range(8):
            crc = (crc >> 1) ^ 0x8408 if crc & 1 else crc >> 1
    crc = ~crc & 0xFFFF
    return ((crc << 8) | (crc >> 8)) & 0xFFFF


_MASK_TABLE = str.maketrans({c: "\x01" for c in "0123456789ABCDEFabcdef"} | {".": "\x00"})


def parse_hex(text: str) -> tuple[bytes, bytes]:
    """Pattern bytes as (values, mask); a mask byte of 0 is a wildcard."""

    if len(text) % 2:
        raise ValueError(f"odd-length pattern {text[:40]}")
    values = bytes.fromhex(text.replace("..", "00"))
    # Each pair is either ".." or two hex digits, so its first character
    # says which.
    mask = text[0::2].translate(_MASK_TABLE).encode("latin-1")
    return values, mask


def demangle(names: list[str]) -> list[str]:
    """Demangle Itanium names the way rizin's demangler printed them.

    That is libiberty without DMGL_VERBOSE: `std::string::rbegin() const`,
    not `std::basic_string<char, ...>::rbegin() const`, which is what plain
    c++filt prints. `c++filt -i` turns the verbose expansion off.
    """

    if not names:
        return []
    completed = subprocess.run(
        ["c++filt", "-i"], input="\n".join(names) + "\n", capture_output=True, text=True,
        check=True,
    )
    lines = completed.stdout.split("\n")
    if len(lines) < len(names):
        raise RuntimeError("c++filt returned fewer names than it was given")
    return lines[: len(names)]


@dataclass
class Line:
    lead: str
    crc_len: int
    crc: int
    total: int
    name: str
    tail: str

    @classmethod
    def parse(cls, text: str) -> "Line":
        tokens = text.split()
        if len(tokens) < 6 or tokens[4] != ":0000":
            raise ValueError(f"unexpected line shape: {text[:120]}")
        rest = tokens[6:]
        tail = ""
        if rest and not rest[0].startswith(":"):
            tail, rest = rest[0], rest[1:]
        if rest:
            raise ValueError(f"more than one name on an imported line: {text[:120]}")
        return cls(tokens[0], int(tokens[1], 16), int(tokens[2], 16), int(tokens[3], 16),
                   tokens[5], tail)

    def tail_style(self) -> str:
        """'after-crc', 'after-lead', or 'either' for the tail's alignment."""

        if not self.tail or not self.crc_len:
            return "trivial"
        run = 0
        for index in range(0, len(self.tail), 2):
            if self.tail[index : index + 2] != "..":
                break
            run += 1
        if run < self.crc_len:
            return "after-crc"
        lead_len = len(self.lead) // 2
        if len(self.tail) // 2 > self.total - lead_len - self.crc_len:
            return "after-lead"
        return "either"

    def realigned(self) -> "Line":
        """This line with a tail stated from the end of the leading pattern
        moved to start after the CRC span."""

        tail = self.tail[2 * self.crc_len :].rstrip(".") if self.tail else ""
        room = max(0, self.total - len(self.lead) // 2 - self.crc_len)
        return Line(self.lead, self.crc_len, self.crc, self.total, self.name, tail[: 2 * room])

    def render(self, name: str) -> str:
        text = f"{self.lead} {self.crc_len:02X} {self.crc:04X} {self.total:04X} :0000 {name}"
        return f"{text} {self.tail}" if self.tail else text


@dataclass
class Function:
    name: str
    values: bytes
    mask: bytes


class Reference:
    """Every function of one target directory, byte for byte, with its name."""

    def __init__(self, binary_format: str) -> None:
        self.binary_format = binary_format
        self.by_shape: dict[tuple[int, int], list[Function]] = defaultdict(list)
        self.by_spelling: dict[str, set[str]] = defaultdict(set)
        self.demangled: dict[str, str] = {}
        self.by_name: dict[str, list[Function]] = defaultdict(list)
        self.names: set[str] = set()
        self._seen: set[int] = set()
        self.functions = 0
        self.too_long = 0

    def add_line(self, text: str) -> None:
        tokens = text.split()
        name = tokens[5]
        # Builds of one library share most functions byte for byte.
        identity = hash((name, tokens[0], tokens[3]))
        if identity in self._seen:
            return
        self._seen.add(identity)
        values, mask = parse_hex(tokens[0])
        total = int(tokens[3], 16)
        self.names.add(name)
        if len(values) < total:
            # Longer than the leading pattern can state; only the name is usable.
            self.too_long += 1
            return
        first = values[0] if total and mask[0] else -1
        function = Function(name, values[:total], mask[:total])
        self.by_shape[(total, first)].append(function)
        self.by_name[name].append(function)
        self.functions += 1

    def index_spellings(self) -> None:
        names = sorted(self.names)
        if self.binary_format == "pe":
            for name in names:
                self.by_spelling[pe_spelling(name)].add(name)
            return
        for name, demangled in zip(names, demangle(names)):
            self.demangled[name] = demangled
            for spelling in elf_spellings(demangled):
                self.by_spelling[spelling].add(name)
            # C names demangle to themselves and were imported verbatim.
            self.by_spelling[name].add(name)

    def candidates(self, total: int, first: int | None) -> list[Function]:
        found = list(self.by_shape.get((total, -1), ()))
        if first is None:
            for (length, leading), functions in self.by_shape.items():
                if length == total and leading != -1:
                    found.extend(functions)
            return found
        return found + list(self.by_shape.get((total, first), ()))

    def one_routine(self, names: set[str]) -> str | None:
        """The name to use when several names are one routine, else None.

        An Itanium constructor or destructor has several symbols (C1/C2,
        D0/D1/D2) that label one definition and demangle identically; any of
        them names the code correctly, so the smallest is taken.
        """

        if len(names) > 1 and self.binary_format == "elf":
            forms = {self.demangled.get(name) for name in names}
            if len(forms) == 1 and None not in forms:
                return min(names)
        return None

    def spelled(self, imported: str) -> set[str]:
        # Spellings are cut at the import's length limit when they are
        # indexed, so a name the import truncated is found exactly.
        return self.by_spelling.get(imported, set())


def agrees(line: Line, lead: tuple[bytes, bytes], tail: tuple[bytes, bytes],
           function: Function) -> bool | None:
    """Whether a line's bytes agree with a function's.

    Returns None when they agree wherever both state a byte but the CRC span
    covers a byte the function leaves to a relocation, so the CRC cannot be
    checked.
    """

    values, mask = function.values, function.mask
    lead_values, lead_mask = lead
    for index in range(min(len(lead_values), line.total)):
        if lead_mask[index] and mask[index] and lead_values[index] != values[index]:
            return False
    crc_start = len(lead_values)
    crc_end = crc_start + line.crc_len
    if crc_end > line.total:
        return False
    checked = True
    if line.crc_len:
        if all(mask[crc_start:crc_end]):
            if crc16(values[crc_start:crc_end]) != line.crc:
                return False
        else:
            checked = False
    tail_values, tail_mask = tail
    for offset in range(min(len(tail_values), line.total - crc_end)):
        index = crc_end + offset
        if tail_mask[offset] and mask[index] and tail_values[offset] != values[index]:
            return False
    return True if checked else None


def by_bytes(line: Line, reference: Reference) -> set[str]:
    lead = parse_hex(line.lead)
    tail = parse_hex(line.tail) if line.tail else (b"", b"")
    first = lead[0][0] if lead[1] and lead[1][0] else None
    strong: set[str] = set()
    weak: set[str] = set()
    for function in reference.candidates(line.total, first):
        verdict = agrees(line, lead, tail, function)
        if verdict:
            strong.add(function.name)
        elif verdict is None:
            weak.add(function.name)
    return strong or weak


def among(line: Line, names: set[str], reference: Reference) -> set[str]:
    """The names whose functions a line's stated bytes agree with.

    Only ever asked about names the spelling already narrowed down to, so the
    function may run longer than the imported line says: rizin measured
    functions by analysis, neverd-sigmaker by symbol extent, and the two
    disagree about trailing padding and split-off cold parts.
    """

    lead = parse_hex(line.lead)
    tail = parse_hex(line.tail) if line.tail else (b"", b"")
    agreeing = set()
    for name in names:
        for function in reference.by_name.get(name, ()):
            if len(function.values) < line.total:
                continue
            clipped = Function(name, function.values[: line.total], function.mask[: line.total])
            if agrees(line, lead, tail, clipped):
                agreeing.add(name)
    return agreeing


def resolve(line: Line, reference: Reference) -> tuple[str | None, str]:
    """The linkage name for an imported line, and how it was settled."""

    matched = by_bytes(line, reference)
    if len(matched) == 1:
        return next(iter(matched)), "bytes"
    spelled = reference.spelled(line.name)
    if matched:
        # The bytes are shared; the imported spelling may still pick one.
        both = matched & spelled
        if len(both) == 1:
            return next(iter(both)), "bytes"
        alias = reference.one_routine(both or matched)
        if alias is not None:
            return alias, "bytes"
    if is_artifact(line.name, reference.binary_format):
        return None, "artifact"
    if len(spelled) == 1:
        return next(iter(spelled)), "spelling"
    alias = reference.one_routine(spelled)
    if alias is not None:
        return alias, "spelling"
    if len(spelled) > 1:
        # Several names spell the same; the bytes may still tell them apart.
        agreeing = among(line, spelled, reference)
        if len(agreeing) == 1:
            return next(iter(agreeing)), "bytes"
        alias = reference.one_routine(agreeing)
        if alias is not None:
            return alias, "bytes"
    elif is_verbatim(line.name, reference.binary_format):
        return line.name, "verbatim"
    return None, "unresolved"


@dataclass
class FileReport:
    lines: int = 0
    by_bytes: int = 0
    by_spelling: int = 0
    already_conforming: int = 0
    verbatim: int = 0
    removed_artifacts: int = 0
    unresolved: int = 0
    realigned_tails: int = 0
    undecided_tails: int = 0
    unresolved_names: list[str] = field(default_factory=list)
    removed_names: list[str] = field(default_factory=list)


def file_tail_style(lines: list[Line]) -> str | None:
    """The alignment a file's undecided tails take: that of at least 95% of
    the tails the file settles, or None."""

    styles = Counter(line.tail_style() for line in lines)
    settled = styles["after-crc"] + styles["after-lead"]
    if not settled:
        return None
    for style in ("after-crc", "after-lead"):
        if styles[style] >= 0.95 * settled:
            return style
    return None


def align(line: Line, reference: Reference, default: str | None) -> tuple[Line, str]:
    style = line.tail_style()
    if style == "either":
        early = line.realigned()
        as_is = bool(by_bytes(line, reference))
        moved = bool(by_bytes(early, reference))
        if as_is == moved:
            # Function extents differ between rizin and neverd-sigmaker, so
            # the strict comparison often says nothing; compare against the
            # functions the imported name can stand for instead.
            spelled = reference.spelled(line.name)
            if spelled:
                as_is = bool(among(line, spelled, reference))
                moved = bool(among(early, spelled, reference))
        if as_is != moved:
            style = "after-crc" if as_is else "after-lead"
        elif default is not None:
            style = default
        else:
            return line, "undecided"
    if style == "after-lead":
        return line.realigned(), "realigned"
    return line, "kept"


def migrate_file(path: Path, reference: Reference, report: FileReport) -> list[str]:
    texts = path.read_text(encoding="utf-8").splitlines()
    parsed = [
        Line.parse(raw.strip())
        for raw in texts
        if raw.strip() and not raw.strip().startswith((";", "#")) and raw.strip() != "---"
    ]
    default = file_tail_style(parsed)
    output = []
    for raw in texts:
        text = raw.strip()
        if not text or text.startswith((";", "#")) or text == "---":
            output.append(raw)
            continue
        line, alignment = align(Line.parse(text), reference, default)
        report.lines += 1
        if alignment == "realigned":
            report.realigned_tails += 1
            text = line.render(line.name)
        elif alignment == "undecided":
            report.undecided_tails += 1
        name, how = resolve(line, reference)
        if how == "artifact":
            report.removed_artifacts += 1
            report.removed_names.append(line.name)
            continue
        if name is None:
            report.unresolved += 1
            report.unresolved_names.append(line.name)
            output.append(text)
            continue
        if how == "verbatim":
            report.verbatim += 1
        elif name == line.name:
            report.already_conforming += 1
        elif how == "bytes":
            report.by_bytes += 1
        else:
            report.by_spelling += 1
        output.append(line.render(name))
    return output


def build_pe_reference(sigmaker: Path, assets: Path, arch: str, work: Path) -> Reference:
    reference = Reference("pe")
    machine = PE_TARGETS[arch][1]
    manifests = sorted(assets.glob(f"*-{arch}.json"))
    if not manifests:
        raise SystemExit(f"no {arch} assets in {assets}")
    for manifest_path in manifests:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        unpacked = work / manifest["asset"]
        unpacked.mkdir(parents=True)
        subprocess.run(
            ["tar", "--zstd", "-xf", str(assets / manifest["archive"]["name"]), "-C", str(unpacked)],
            check=True,
        )
        libraries = sorted(
            str(path) for path in unpacked.rglob("*")
            if path.is_file() and path.suffix.lower() in (".lib", ".obj")
        )
        out = work / f"{manifest['asset']}.ref.pat"
        subprocess.run(
            [str(sigmaker), *libraries, "-o", str(out), "--machine", machine,
             "--leading", str(WHOLE_FUNCTION), "--tail", "0", "--min-size", "1"],
            check=True, stdout=subprocess.DEVNULL,
        )
        for text in out.read_text(encoding="utf-8").splitlines():
            if text.strip():
                reference.add_line(text)
        shutil.rmtree(unpacked)
        out.unlink()
    reference.index_spellings()
    return reference


def load_reference(directory: Path, binary_format: str) -> Reference:
    """Reference lines already generated, one or more .pat files per target."""

    reference = Reference(binary_format)
    files = sorted(directory.glob("*.pat"))
    if not files:
        raise SystemExit(f"no reference .pat files in {directory}")
    for path in files:
        for text in path.read_text(encoding="utf-8").splitlines():
            if text.strip():
                reference.add_line(text)
    reference.index_spellings()
    return reference


def imported_files(tree: Path, revision: str, directory: str) -> list[Path]:
    try:
        listing = subprocess.run(
            ["git", "-C", str(tree), "ls-tree", "--name-only", f"{revision}:{directory}"],
            check=True, capture_output=True, text=True,
        ).stdout.split()
    except subprocess.CalledProcessError:
        return []
    return [tree / directory / name for name in listing if name.endswith(".pat")]


def migrate_directory(tree: Path, directory: str, files: list[Path], reference: Reference,
                      summary: dict[str, dict], verify_with: Path | None) -> None:
    print(f"{directory}: {reference.functions} reference functions, "
          f"{len(reference.names)} names", flush=True)
    for path in files:
        report = FileReport()
        lines = migrate_file(path, reference, report)
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        if verify_with is not None:
            # The loader rejects a whole directory for one bad line.
            subprocess.run([str(verify_with), "--verify", str(path)], check=True,
                           stdout=subprocess.DEVNULL)
        key = path.relative_to(tree).as_posix()
        summary[key] = report.__dict__
        print(
            f"{key}: {report.lines} lines, {report.by_bytes} renamed by bytes, "
            f"{report.by_spelling} by spelling, {report.already_conforming} already "
            f"conforming, {report.verbatim} C names kept, "
            f"{report.removed_artifacts} non-function lines removed, "
            f"{report.unresolved} unresolved; {report.realigned_tails} tails realigned, "
            f"{report.undecided_tails} undecided",
            flush=True,
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--tree", type=Path, default=Path("."),
                        help="the signatures repository checkout")
    parser.add_argument("--imported-from", default="0a3da7a",
                        help="the commit that imported the rizin files")
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--work", type=Path, default=None)
    parser.add_argument("--verify-with", type=Path, default=None,
                        help="neverd-sigmaker to read every rewritten file back with")
    pe = parser.add_argument_group("PE directories, referenced from a library release")
    pe.add_argument("--sigmaker", type=Path)
    pe.add_argument("--assets", type=Path,
                    help="directory with the library release's archives and manifests")
    pe.add_argument("--arch", action="append", choices=sorted(PE_TARGETS), default=[])
    other = parser.add_argument_group("any directory, referenced from generated lines")
    other.add_argument("--directory", action="append", default=[],
                       help="target directory such as elf/x86/64 (repeatable)")
    other.add_argument("--references", type=Path,
                       help="root holding <directory>/*.pat reference lines")
    args = parser.parse_args(argv)

    summary: dict[str, dict] = {}
    for arch in args.arch:
        if args.sigmaker is None or args.assets is None:
            parser.error("--arch needs --sigmaker and --assets")
        directory = PE_TARGETS[arch][0]
        files = imported_files(args.tree, args.imported_from, directory)
        if not files:
            continue
        with tempfile.TemporaryDirectory(dir=args.work) as scratch:
            reference = build_pe_reference(args.sigmaker, args.assets, arch, Path(scratch))
        migrate_directory(args.tree, directory, files, reference, summary, args.verify_with)
    for directory in args.directory:
        if args.references is None:
            parser.error("--directory needs --references")
        files = imported_files(args.tree, args.imported_from, directory)
        if not files:
            continue
        reference = load_reference(args.references / directory, directory.split("/")[0])
        migrate_directory(args.tree, directory, files, reference, summary, args.verify_with)

    args.report.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    totals = Counter()
    for report in summary.values():
        for key in ("lines", "by_bytes", "by_spelling", "already_conforming", "verbatim",
                    "removed_artifacts", "unresolved", "realigned_tails", "undecided_tails"):
            totals[key] += report[key]
    print(f"total: {dict(totals)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
